image: rscohn2/oneapi-spec:latest

stages:
  - publish
  
cache:
  paths:
    - public
    
pages:
  stage: publish
  script:
  - python3 -m venv venv
  - . venv/bin/activate
  - pip install --upgrade --quiet -r requirements.txt
  - python doc.py html
  - python doc.py latexpdf
  - python doc.py spelling
  - mkdir public
  - cp -r build/html public/$CI_COMMIT_REF_NAME
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
    - public
    - build
