image: rscohn2/oneapi-spec:latest

stages:
  - publish
  
# Keeps public directory from previous runs
# so gitlab pages will include them, too
# unless cache is purged
cache:
  paths:
    - public
    
pages:
  stage: publish
  script:
  - python3 -m venv venv
  - . venv/bin/activate
  - pip install --upgrade --quiet -r requirements.txt
  - python doc.py html
  - python doc.py latexpdf
  - python doc.py spelling
  - mkdir -p public
  - cp -r build/html public/$CI_COMMIT_REF_NAME
  artifacts:
    # name is unique for branch so it will keep multiple branches
    name: "$CI_COMMIT_REF_NAME"
    paths:
    - public
    - build
