image: rscohn2/oneapi-spec:latest

before_script:
  - python3 -m venv venv
  - . venv/bin/activate
  - pip install --upgrade --quiet -r requirements.txt
  - python doc.py html
  - python doc.py latexpdf
  - python doc.py spelling

test:
  stage: test
  script:
  - echo Branch is not dpcpp, publishing as an artifact
  artifacts:
    paths:
    - build
  except:
  - dpcpp
  
pages:
  stage: deploy
  script:
  - cp -r build/html public
  artifacts:
    paths:
    - public
    - build
  only:
  - dpcpp
